version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 1883:1883
    volumes:
        - ./data/:/var/lib/rabbitmq
        - ./log/:/var/log/rabbitmq
        - ./enabled_plugins:/etc/rabbitmq/enabled_plugins
        - ./conf.d:/etc/rabbitmq/conf.d
